test_set1 = [{"dateFormat": "dd-mm-yyyy", "thousandSeparator": ",", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": ",", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": ",", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": ".", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": ".", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": ".", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "'", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "'", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "'", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ",", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ",", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ",", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ".", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ".", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ".", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "'", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "'", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "'", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a"},
             {"thousandSeparator": ","},
             {"thousandSeparator": "."},
             {"thousandSeparator": "'"},
             {"decimalSeparator": "'"},
             {"decimalSeparator": ","},
             {"decimalSeparator": "."},
             {"decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": ","},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "."},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ","},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "."},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyyy", "decimalSeparator": "."},
             {"dateFormat": "dd-mm-yyyy", "decimalSeparator": "'"},
             {"thousandSeparator": ",", "decimalSeparator": ","},
             {"thousandSeparator": ",", "decimalSeparator": "."},
             {"thousandSeparator": ",", "decimalSeparator": "'"},
             {"thousandSeparator": ".", "decimalSeparator": ","},
             {"thousandSeparator": ".", "decimalSeparator": "."},
             {"thousandSeparator": ".", "decimalSeparator": "'"},
             {"thousandSeparator": "'", "decimalSeparator": ","},
             {"thousandSeparator": "'", "decimalSeparator": "."},
             {"thousandSeparator": "'", "decimalSeparator": "'"}
             ]

test_set2 = [{"dateFormat": "dd-m-yyy", "thousandSeparator": ",", "decimalSeparator": ","},
             {"dateFormat": "mm-dd-yyyy", "thousandSeparator": ",", "decimalSeparator": "."},
             {"dateFormat": "11-22-3333", "thousandSeparator": ",", "decimalSeparator": "'"},
             {"dateFormat": "yyyy-mm-dd", "thousandSeparator": ".", "decimalSeparator": ","},
             {"dateFormat": "dd-mm1-yyyy", "thousandSeparator": ".", "decimalSeparator": "."},
             {"dateFormat": "dd-ma-yyyy", "thousandSeparator": "2", "decimalSeparator": "'"},
             {"dateFormat": "da-mm-yyyy", "thousandSeparator": "@", "decimalSeparator": ","},
             {"dateFormat": "ds-mm-yyyy", "thousandSeparator": "#", "decimalSeparator": "."},
             {"dateFormat": "dq-mm-yyyy", "thousandSeparator": "", "decimalSeparator": "'"},
             {"dateFormat": "a-mm-yyyy h:mm:ss a", "thousandSeparator": "", "decimalSeparator": "^"},
             {"dateFormat": "vd-mm-yyyy h:mm:ss a", "thousandSeparator": ",", "decimalSeparator": ")"},
             {"dateFormat": "ds-mm-yyyy h:mm:ss a", "thousandSeparator": "d,", "decimalSeparator": "!"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "s.", "decimalSeparator": "~"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ".", "decimalSeparator": "}"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": ".", "decimalSeparator": "add"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "1", "decimalSeparator": "a"},
             {"dateFormat": "dd-mm-yyyy h:mm:ss a", "thousandSeparator": "'", "decimalSeparator": ""},
             {"dateFormat": "dd-mm-yyyy h:mm:ss ax", "thousandSeparator": "'1", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyya"},
             {"dateFormat": "dd-mm-yyyy sh:mm:ss a"},
             {"thousandSeparator": "/"},
             {"thousandSeparator": "_"},
             {"thousandSeparator": "]"},
             {"decimalSeparator": "|"},
             {"decimalSeparator": "q"},
             {"decimalSeparator": ">"},
             {"decimalSeparator": "<"},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "1"},
             {"dateFormat": "dd-mm-yyyy", "thousandSeparator": "~"},
             {"dateFormat": "dd-mm-yyy h:mm:ss a", "thousandSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy :mm:ss a", "decimalSeparator": ","},
             {"dateFormat": "dd-mm-yyy h:mm:ss a", "decimalSeparator": "."},
             {"dateFormat": "dd-mmyyyy h:mm:ss a", "decimalSeparator": "'"},
             {"dateFormat": "dd-mm-yyyy", "decimalSeparator": "a"},
             {"dateFormat": "dd-mm-yyyy", "decimalSeparator": "1"},
             {"dateFormat": "dd-mm-yyyy", "decimalSeparator": ".."},
             {"thousandSeparator": ",", "decimalSeparator": ",,,"},
             {"thousandSeparator": ">", "decimalSeparator": "."},
             {"thousandSeparator": "<<", "decimalSeparator": "'"},
             {"thousandSeparator": "#", "decimalSeparator": ","},
             {"thousandSeparator": "and", "decimalSeparator": "."},
             {"thousandSeparator": "", "decimalSeparator": "'"},
             {"thousandSeparator": "pa", "decimalSeparator": ","},
             {"thousandSeparator": "Z", "decimalSeparator": "."},
             {"thousandSeparator": "000", "decimalSeparator": "'"},
             {"decimalSeparator": "!"},
             {"decimalSeparator": "@"},
             {"decimalSeparator": "#"},
             {"decimalSeparator": "$"},
             {"decimalSeparator": "%"},
             {"decimalSeparator": "^"},
             {"decimalSeparator": "&"},
             {"decimalSeparator": "*"},
             {"decimalSeparator": "("},
             {"decimalSeparator": ")"},
             {"decimalSeparator": "~"},
             {"decimalSeparator": "_"},
             {"decimalSeparator": "="},
             {"decimalSeparator": "1"},
             {"decimalSeparator": "2"},
             {"decimalSeparator": "3"},
             {"decimalSeparator": "4"},
             {"decimalSeparator": "5"},
             {"decimalSeparator": "6"},
             {"decimalSeparator": "7"},
             {"decimalSeparator": "8"},
             {"decimalSeparator": "9"},
             {"decimalSeparator": "0"},
             {"decimalSeparator": "-"},
             {"decimalSeparator": "="},
             {"decimalSeparator": " "},
             {"decimalSeparator": "q"},
             {"decimalSeparator": "w"},
             {"decimalSeparator": "e"},
             {"decimalSeparator": "r"},
             {"decimalSeparator": "t"},
             {"decimalSeparator": "y"},
             {"decimalSeparator": "u"},
             {"decimalSeparator": "i"},
             {"decimalSeparator": "o"},
             {"decimalSeparator": "p"},
             {"decimalSeparator": "["},
             {"decimalSeparator": "]"},
             {"decimalSeparator": "{"},
             {"decimalSeparator": "}"},
             {"decimalSeparator": "\\"},
             {"decimalSeparator": "a"},
             {"decimalSeparator": "s"},
             {"decimalSeparator": "d"},
             {"decimalSeparator": "f"},
             {"decimalSeparator": "g"},
             {"decimalSeparator": "h"},
             {"decimalSeparator": "j"},
             {"decimalSeparator": "k"},
             {"decimalSeparator": "l"},
             {"decimalSeparator": ";"},
             {"decimalSeparator": "z"},
             {"decimalSeparator": "x"},
             {"decimalSeparator": "c"},
             {"decimalSeparator": "v"},
             {"decimalSeparator": "b"},
             {"decimalSeparator": "n"},
             {"decimalSeparator": "m"},
             {"decimalSeparator": "/"}
             ]